### PR TITLE
Merge OCBC performance improvements.

### PR DESCRIPTION
**Pull request by andreapiso**
This Pull Request significantly speeds up the veritas toolkit by a factor of 10 on the following flows:

- Credit scoring use cases.
- "Classification" Marketing use cases

"Uplift" marketing use cases are not affected by the speedup at this moment - as they do not use the optimised code. 

We will attach correctness tests and performance comparison between this branch and master over the weekend.

@mas-veritas2  for your review!

### CODE REVIEW

**Comment by andreapiso** [comment]
Equivalence Test:

Credit Scoring use case, `evaluate()` method

image

image

The metrics are unchanged before and after optimisation

**Comment by andreapiso** [comment]
Credit Scoring Use Case, `evaluate()` method - privileged vs unprivileged groups

image

image

Metrics are unchanged after optimisation

**Comment by andreapiso** [comment]
Credit Scoring use case - privileged vs unprivileged groups - Marital Status

image

image

In this case we have observed minimal differences in the computation of the AUC - as the area under the curve is still an approximation, which we changed slightly to be able to vectorize over `np.trapz`. Difference should be negligible.

**Comment by andreapiso** [comment]
Credit Scoring Use Case - `tradeoff()` method

image

image

Metrics are unchanged after optimisation.

**Comment by andreapiso** [comment]
Credit Scoring Use Case - Feature Importance 

image

image

Metrics are unchanged after optimisation

**Comment by andreapiso** [comment]
Run Time differential before and after optimization - Runtime is around 10x faster across dataset of various sizes

image

**Comment by andreapiso** [comment]
Function-by-function execution time of optimised code vs original - 90.1% gain vs unoptimised code. 

image

**Comment by andreapiso** [comment]
Marketing Use case (propensity - rejection) 

All metrics are the same after optimisation (including AUC calculation).

**Overall Model Metrics**

image

image

**Privileged vs Unprivileged - Gender **
image

image

**Privileged vs Unprivileged - Marital Status**

image

image

**Tradeoff**

image

image

**Feature Importance**

image

image

**Review by veritas-toolkit — APPROVED** [review]

**Pull request merged**
